;; GitHub Color Theme for Emacs.
;;
(theme-roller-make-theme
 "Github"
 ((background-color . "#f8f8ff")
  (background-mode . light)
  (border-color . "black")
  (cursor-color . "#000000")
  (foreground-color . "#000000")
  (mouse-color . "#bcd5fa"))
 :base-font          (:stipple nil :background "#f8f8ff" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal)
 :selection          (:background "#bcd5fa")
 :brief-highlight    (:background "#acc3e6")
 :durable-highlight  (:background "#dddddd")
 :link               (:foreground "blue1" :underline t)
 :mode-line          (:background "#acc3e6" :foreground "black" :box (:line-width -1 :style released-button))
 :minibuffer-prompt  (:foreground "#445588")
 :code-variable      (:foreground "#0086b3")
 :code-reference     (nil)
 :code-constant      (:foreground "#990073")
 :code-type          (:foreground "#445588")
 :code-keyword       (:bold t :weight bold)
 :code-string        (:foreground "#dd1144")
 :code-comment       (:italic t :foreground "#999988" :slant italic)
 :code-documentation (:foreground "#dd1144")
 :code-function      (:foreground "#990000")
 :code-meta          (:foreground "Orange")
 :code-error         (:bold t :background "#ff6347")
 :code-warning       (:bold t :background "#ffe4b5")
 :diff-removed       (:background "IndianRed1")
 :diff-changed       (:background "burlywood3")
 :diff-info          (:background "LightSteelBlue3")
 :diff-added         (:background "DarkOliveGreen3")
 :diff-context       (:background "gray90")
 :code-escape-char   (:foreground "#009926"))
