(theme-roller-make-theme "Github"
                         ((background-color . "#f8f8ff")
                          (background-mode . light)
                          (border-color . "black")
                          (cursor-color . "#000000")
                          (foreground-color . "#000000")
                          (mouse-color . "#bcd5fa"))
                         :base-font          (:stipple nil :background "#f8f8ff" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal)
                         :selection          (:background "#bcd5fa")
                         :brief-highlight    (:background "#acc3e6")
                         :durable-highlight  (:background "#dddddd")
                         :link               (:foreground "blue1" :underline t)
                         :mode-line          (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button) :height 0.85)
                         :minibuffer-prompt  (:foreground "#445588")
                         :code-variable      (:foreground "#0086b3")
                         :code-reference     (nil)
                         :code-constant      (:foreground "#990073")
                         :code-type          (:foreground "#445588")
                         :code-keyword       (:bold t :weight bold)
                         :code-string        (:foreground "#dd1144")
                         :code-comment       (:italic t :foreground "#999988" :slant italic)
                         :code-documentation (:foreground "#dd1144")
                         :code-function      (:foreground "#990000")
                         :code-meta          (:foreground "Aquamarine")
                         :code-error         (:bold t :foreground "red")
                         :code-warning       (:bold t :foreground "yellow")
                         :diff-removed       (:background "#dd1144")
                         :diff-changed       (:background "#4A410D")
                         :diff-info          (:background "#fff6a9")
                         :diff-added         (:background "#253B22")
                         :code-escape-char   (:foreground "#009926"))
